{
  "mongodb":   {
    "image": "mongo",
    "volumes": ["./mongo_import:/var/import"]
  },
  "redis":     {"image": "redis"},
  "memcached": {"image": "memcached"},
  "mailhog":   {
    "image": "mailhog/mailhog",
    "ports": ["8025:8025"]
  },
  "web": {
    "build": ".",
    "ports": ["3000:3000"],
    "volumes": [".:/var/app"],
    "links": ["mongodb", "redis", "memcached", "mailhog"],
    "env_file": [".env"],
    "environment": {
      "REDIS_URL": "redis://redis:6379"
    }
  },
  "sidekiq": {
    "build": ".",
    "volumes": [".:/var/app"],
    "links": ["mongodb", "redis", "memcached", "mailhog"],
    "env_file": [".env"],
    "environment": {
      "REDIS_URL": "redis://redis:6379"
    },
    "command": "bundle exec sidekiq"
  }
}
